trigger:
  - main

pool: 'Development'

variables:
  - group: 'Android Signing'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: DownloadSecureFile@1
    name: keystore
    inputs:
      secureFile: 'essency-release-key.jks'

  - script: |
      ./gradlew assembleRelease ^
        -Pandroid.injected.signing.store.file="$(keystore.secureFilePath)" ^
        -Pandroid.injected.signing.store.password="$(keystorePassword)" ^
        -Pandroid.injected.signing.key.alias="$(keyAlias)" ^
        -Pandroid.injected.signing.key.password="$(keystorePassword)"
    displayName: '🚀 Build Signed APK'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'app/build/outputs/apk/release/'
      artifactName: 'EssencyStockMovement-release-apk'
